#!/bin/sh
#	~/.config/bspwm/bspwmrc
MOD=Mod4

#	reset config
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

ws1="dev"
ws2="www"
ws3="music"
ws4="other"

bspc monitor -d $ws1 $ws2 $ws3 $ws4
xrandr --output eDP-1 --mode 2736x1824 &
feh --bg-center /home/jscarlet/imgs/gentoo_trans_wp.png

#	autostart
killall "nm-applet"
nm-applet &
xrdb ~/.Xresources &
killall "picom"
picom &
killall "polybar"
$HOME/.config/polybar/launch.sh

#	global prefs
bspc config automatic_scheme	spiral
bspc config border_width		2
bspc config bottom_padding		0
bspc config left_padding		0
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner
bspc config pointer_modifier	shift
bspc config right_padding		0
bspc config split_ratio			0.52
bspc config top_padding			32
bspc config window_gap			26

bspc config borderless_monocle		true
bspc config focus_follows_pointer	true
bspc config gapless_monocle			true
bspc config history_aware_focus		true

#	colors
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#406ea5"
bspc config normal_border_color		"#4c566a"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 state=floating

